[package]
name = "fretcat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["xtask", "standalone"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
fretcat_audio = {path = "./crates/fretcat_audio"}
fretcat_editor = {path = "./crates/fretcat_editor"}
fretcat_plugin = {path = "./crates/fretcat_plugin"}
fretcat_derive = {path = "./crates/fretcat_derive"}

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"

[profile.dev.package."*"]
opt-level = 3
