[package]
name = "fretcat_effects"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = { version = "0.25.0", features = ["derive"]}
rand = "0.8.5"
atomic_refcell = "0.1.10"
downcast-rs = "1.2.0"
dyn-clone = "1.0.12"
