[package]
name = "vizia_core"
version = "0.1.0"
authors = ["George Atkinson"]
license = "MIT"
repository = "https://github.com/vizia/vizia"
edition = "2021"
description = "Core components of vizia"
rust-version = "1.60"

[features]
clipboard = ["copypasta"]
x11 = ["copypasta?/x11"]
wayland = ["copypasta?/wayland"]
embedded_fonts = []

[dependencies]
vizia_derive = { path = "../vizia_derive" }
vizia_storage = { path = "../vizia_storage" }
vizia_id = { path = "../vizia_id" }
vizia_input = { path = "../vizia_input" }
vizia_window = { path = "../vizia_window" }
vizia_style = { path = "../vizia_style"}
accesskit = "0.11.0"

femtovg = "0.7.0"
image = { version = "0.24.6", default-features = false, features = ["png"] } # inherited from femtovg
# morphorm = {path = "../../../morphorm" }
morphorm = "0.6.2"
#morphorm = { path = "../../../morphorm", features = ["rounding"] }
bitflags = "2.1.0"
fnv = "1.0.7"
fluent-bundle = "0.15.2"
fluent-langneg = "0.13"
unic-langid = {version = "0.9", features = ["macros"]}
sys-locale = "0.3.0"
unicode-segmentation = "1.8.0"
copypasta = {version = "0.8.1", optional = true, default-features = false }
instant = "0.1.12"
chrono = "0.4.22"
# cosmic-text = "0.8.0"
cosmic-text = { git="https://github.com/pop-os/cosmic-text", rev="79275d15e857428e9b8874f28413197e878f3788" }
swash = "0.1.8"
log = "0.4.19"
# reqwest = { version = "0.11.9", features = ["blocking"] }

# Required so that doc tests will compile
[dev-dependencies]
vizia_winit = {version = "0.1.0", path = "../vizia_winit" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web_sys = { version = "0.3", package = "web-sys", features = ["console"] }
